name: "FTP"
description: "Upload directory through FTP"
inputs:
  username:
    description: "FTP username"
    required: true
    default: ""
  password:
    description: "FTP password"
    required: true
    default: ""
  server:
    description: "FTP server"
    required: true
    default: ""
  local-directory:
    description: "directory to upload from"
    required: true
    default: "."
  server-directory:
    description: "directory to upload to"
    required: true
    default: "."
runs:
  using: "node12"
  main: "dist/index.js"
